server:
  port: 8081
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: pdf-epub-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/conveter?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password:
  jpa:
    database: mysql
    show-sql: false  #展示SQL语句
    generate-ddl: true  #是否自动建表
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
com:
  path:
    EpubPath: D:\data\pdf\Test\EpubTotal
    PdfPath: D:\data\pdf\Test\PdfTotal
    HtmlPath: D:\data\pdf\Test\HtmlTotal
    TxtPath: D:\data\pdf\Test\TxtTotal
